# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ur5e_planning_grp_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    ur5e_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ur5e_planning_grp_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    
    # Position holding parameters
    allow_nonzero_velocity_at_trajectory_end: false
    allow_partial_joints_goal: false
    
    # Stricter tolerances for position holding
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time_tolerance: 3.0
      
    # State publishing
    state_publish_rate: 50.0
    action_monitor_rate: 20.0